name: Create and Increment Release Tag

on:
  push:
    branches:
      - main

jobs:
  create-and-increment-release-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=latest_tag::$latest_tag"
        id: latest_tag

      - name: Increment tag
        run: |
          latest_tag="${{ steps.latest_tag.outputs.latest_tag }}"
          new_tag=$(echo $latest_tag | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "::set-output name=new_tag::$new_tag"
        id: new_tag

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.new_tag.outputs.new_tag }}
          release_name: Release ${{ steps.new_tag.outputs.new_tag }}
          body: |
            Release ${{ steps.new_tag.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      # Add additional steps here, as needed
