name: Jest Test

on:
  pull_request:
    branches: [ main ]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          yarn: true

      - name: Install Dependencies
        run: yarn install

      - name: Run Jest Tests
        run: yarn test
